[project]
name = "stocks"
version = "0.1.0"
description = "Stock market analysis and tracking application"
authors = [
    {name = "pmlhtra"}
]
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "yfinance (<0.2.50)",
    "requests (<2.33)",
    "pydantic (>=2.13.4,<3.0.0)",
    "python-dotenv (<1.1)",
    "google-generativeai (>=0.8.6,<0.9.0)",
    "pypdf (>=6.15.0,<7.0.0)",
    "beautifulsoup4 (>=4.12.0,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

